name: lazy_indexed_stack

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.0.0

  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.0
          cache: true

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
      - name: Verify Pub Score
        run: ./tool/verify_pub_score.sh 110