name: Semantic Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Pull Request
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}